[package]
name = "elayr"
version = "0.1.0"
authors = [
        "Nicolas Argyriou <argyriou@etu.unistra.fr>",
        "Quentin Gliech <quentin.gliech@etu.unistra.fr>"
]

[lib]
crate-type = ["rlib", "dylib"]

[dependencies.nom]
version = "^3.2"
